# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 9082
## 数据源配置
#spring:
#    # redis 配置
#    redis:
#        # 地址
#        host: 127.0.0.1
#        # 端口，默认为6379
#        port: 6379
#        # 数据库索引
#        database: 0
#        # 密码
#        password:
#        # 连接超时时间
#        timeout: 10s
#        lettuce:
#            pool:
#                # 连接池中的最小空闲连接
#                min-idle: 0
#                # 连接池中的最大空闲连接
#                max-idle: 8
#                # 连接池的最大数据库连接数
#                max-active: 8
#                # #连接池最大阻塞等待时间（使用负值表示没有限制）
#                max-wait: -1ms

cable:
  admin-url: http://08a9e10d28684227.natapp.cc:56657/biz/stream/getCameraListByAreaCode
  admin-server-hostname: 223359e0dff61097.natapp.cc
  admin-server-port: 62637
  python_url: http://2d9ee526be110226.natapp.cc:54885/_t_